//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Advertisement
{
	public virtual DateTime PublicationDate
	{
		get;
		set;
	}

	public virtual DateTime ClosingDate
	{
		get;
		set;
	}

	public virtual string Description
	{
		get;
		set;
	}

	public virtual int Price
	{
		get;
		set;
	}

	public virtual IEnumerable<Offer> Offer
	{
		get;
		set;
	}

}

