//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee
{
	public virtual int LegalPersonId
	{
		get;
		set;
	}

	public virtual int PhysicalPersonId
	{
		get;
		set;
	}

	public virtual int PositionId
	{
		get;
		set;
	}

	public virtual DateTime DateFrom
	{
		get;
		set;
	}

	public virtual DateTime DateTo
	{
		get;
		set;
	}

	public virtual Position Position
	{
		get;
		set;
	}

}

