//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Inspection : RepairCause
{
	public virtual DateTime Date
	{
		get;
		set;
	}

	public virtual bool isRepeated
	{
		get;
		set;
	}

	public virtual InspectionResult DoCheck()
	{
		throw new System.NotImplementedException();
	}

}

