//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InsuranceCase
{
	public virtual object Description
	{
		get;
		set;
	}

	public virtual InsuranceCase Type
	{
		get;
		set;
	}

	public virtual Accident Accident
	{
		get;
		set;
	}

}

