//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Offer
{
	public virtual int PersonId
	{
		get;
		set;
	}

	public virtual int AdvertisementId
	{
		get;
		set;
	}

	public virtual DateTime ValidTill
	{
		get;
		set;
	}

	public virtual int Price
	{
		get;
		set;
	}

}

