//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Party
{
	public virtual string StateProvidedId
	{
		get;
		set;
	}

	public virtual IEnumerable<AccidentParty> AccidentParty
	{
		get;
		set;
	}

}

