//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Person3 : Party3
{
	public virtual object FullName
	{
		get;
		set;
	}

	public virtual IEnumerable<Ownership3> Ownership
	{
		get;
		set;
	}

	public virtual IEnumerable<Offer3> Offer
	{
		get;
		set;
	}

	public virtual Contact3 Contact
	{
		get;
		set;
	}

	public virtual void SendOffer(Offer3 offer)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AcceptOffer(Offer3 offer)
	{
		throw new System.NotImplementedException();
	}

}

