//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PhysicalPerson : Person
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Surname
	{
		get;
		set;
	}

	public virtual IEnumerable<Employee> Employee
	{
		get;
		set;
	}

}

