//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class ServiceCase
{
	public virtual DateTime Date
	{
		get;
		set;
	}

	public virtual IEnumerable<ServiceOperation> ServiceOperation
	{
		get;
		set;
	}

}

